spring:
  application:
    name: product-mq-consumer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: /actuator/health
    
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
    
server:
  port: 9013
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0